POSTTEST1_090
Praktikum-Informatika-Mulawarman/B2_PBO pull request #18
Opened 2022-03-29 14:51 UTC by Be-Frisk

2022-04-04 08:32 UTC, adefiqri12 requested changes
push dengan folder sesuai format yang diminta NIMLENGKAP_NAMA LENGKAP

2022-04-05 14:50 UTC, Be-Frisk commented
Posttest2 090_Friska Eunike Ma'ga

2022-04-05 15:51 UTC, adefiqri12 approved these changes
oke

2022-04-06 02:56 UTC, adefiqri12 approved these changes

2022-04-13 13:36 UTC, merged